backend:
  name: git-gateway

  branch: main

publish_mode: editorial_workflow

media_folder: "_site/img"

public_folder: "/img"

collections:
  - name: "blog"

    label: "Blog"

    folder: "posts"

    create: true

    slug: "{{slug}}"

    fields:
      - { label: "Title", name: "title", widget: "string" }

      - { label: "Description", name: "description", widget: "string" }

      - { label: "Date", name: "date", widget: "datetime" }

      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }

      - { label: "Featured Image", name: "image", widget: "image" }

      - { label: "Body", name: "body", widget: "markdown" }
